// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PointCloud.proto

package de.ostfalia.robocup.message;

public final class MsgPointCloud	 {
  private MsgPointCloud	() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PointCloudOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // repeated .protobuf.Point point = 1;
    java.util.List<de.ostfalia.robocup.message.MsgPoint.Point> 
        getPointList();
    de.ostfalia.robocup.message.MsgPoint.Point getPoint(int index);
    int getPointCount();
  }
  public static final class PointCloud extends
      com.google.protobuf.GeneratedMessageLite
      implements PointCloudOrBuilder {
    // Use PointCloud.newBuilder() to construct.
    private PointCloud(Builder builder) {
      super(builder);
    }
    private PointCloud(boolean noInit) {}
    
    private static final PointCloud defaultInstance;
    public static PointCloud getDefaultInstance() {
      return defaultInstance;
    }
    
    public PointCloud getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // repeated .protobuf.Point point = 1;
    public static final int POINT_FIELD_NUMBER = 1;
    private java.util.List<de.ostfalia.robocup.message.MsgPoint.Point> point_;
    public java.util.List<de.ostfalia.robocup.message.MsgPoint.Point> getPointList() {
      return point_;
    }
    public java.util.List<? extends de.ostfalia.robocup.message.MsgPoint.PointOrBuilder> 
        getPointOrBuilderList() {
      return point_;
    }
    public int getPointCount() {
      return point_.size();
    }
    public de.ostfalia.robocup.message.MsgPoint.Point getPoint(int index) {
      return point_.get(index);
    }
    public de.ostfalia.robocup.message.MsgPoint.PointOrBuilder getPointOrBuilder(
        int index) {
      return point_.get(index);
    }
    
    private void initFields() {
      point_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getPointCount(); i++) {
        if (!getPoint(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < point_.size(); i++) {
        output.writeMessage(1, point_.get(i));
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < point_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, point_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static de.ostfalia.robocup.message.MsgPointCloud	.PointCloud parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.ostfalia.robocup.message.MsgPointCloud	.PointCloud parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.ostfalia.robocup.message.MsgPointCloud	.PointCloud parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.ostfalia.robocup.message.MsgPointCloud	.PointCloud parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.ostfalia.robocup.message.MsgPointCloud	.PointCloud parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.ostfalia.robocup.message.MsgPointCloud	.PointCloud parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.ostfalia.robocup.message.MsgPointCloud	.PointCloud parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.ostfalia.robocup.message.MsgPointCloud	.PointCloud parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.ostfalia.robocup.message.MsgPointCloud	.PointCloud parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.ostfalia.robocup.message.MsgPointCloud	.PointCloud parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.ostfalia.robocup.message.MsgPointCloud	.PointCloud prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          de.ostfalia.robocup.message.MsgPointCloud	.PointCloud, Builder>
        implements de.ostfalia.robocup.message.MsgPointCloud	.PointCloudOrBuilder {
      // Construct using de.ostfalia.robocup.message.MsgPointCloud	.PointCloud.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        point_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public de.ostfalia.robocup.message.MsgPointCloud	.PointCloud getDefaultInstanceForType() {
        return de.ostfalia.robocup.message.MsgPointCloud	.PointCloud.getDefaultInstance();
      }
      
      public de.ostfalia.robocup.message.MsgPointCloud	.PointCloud build() {
        de.ostfalia.robocup.message.MsgPointCloud	.PointCloud result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private de.ostfalia.robocup.message.MsgPointCloud	.PointCloud buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        de.ostfalia.robocup.message.MsgPointCloud	.PointCloud result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public de.ostfalia.robocup.message.MsgPointCloud	.PointCloud buildPartial() {
        de.ostfalia.robocup.message.MsgPointCloud	.PointCloud result = new de.ostfalia.robocup.message.MsgPointCloud	.PointCloud(this);
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          point_ = java.util.Collections.unmodifiableList(point_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.point_ = point_;
        return result;
      }
      
      public Builder mergeFrom(de.ostfalia.robocup.message.MsgPointCloud	.PointCloud other) {
        if (other == de.ostfalia.robocup.message.MsgPointCloud	.PointCloud.getDefaultInstance()) return this;
        if (!other.point_.isEmpty()) {
          if (point_.isEmpty()) {
            point_ = other.point_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePointIsMutable();
            point_.addAll(other.point_);
          }
          
        }
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getPointCount(); i++) {
          if (!getPoint(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              de.ostfalia.robocup.message.MsgPoint.Point.Builder subBuilder = de.ostfalia.robocup.message.MsgPoint.Point.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPoint(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .protobuf.Point point = 1;
      private java.util.List<de.ostfalia.robocup.message.MsgPoint.Point> point_ =
        java.util.Collections.emptyList();
      private void ensurePointIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          point_ = new java.util.ArrayList<de.ostfalia.robocup.message.MsgPoint.Point>(point_);
          bitField0_ |= 0x00000001;
         }
      }
      
      public java.util.List<de.ostfalia.robocup.message.MsgPoint.Point> getPointList() {
        return java.util.Collections.unmodifiableList(point_);
      }
      public int getPointCount() {
        return point_.size();
      }
      public de.ostfalia.robocup.message.MsgPoint.Point getPoint(int index) {
        return point_.get(index);
      }
      public Builder setPoint(
          int index, de.ostfalia.robocup.message.MsgPoint.Point value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePointIsMutable();
        point_.set(index, value);
        
        return this;
      }
      public Builder setPoint(
          int index, de.ostfalia.robocup.message.MsgPoint.Point.Builder builderForValue) {
        ensurePointIsMutable();
        point_.set(index, builderForValue.build());
        
        return this;
      }
      public Builder addPoint(de.ostfalia.robocup.message.MsgPoint.Point value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePointIsMutable();
        point_.add(value);
        
        return this;
      }
      public Builder addPoint(
          int index, de.ostfalia.robocup.message.MsgPoint.Point value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePointIsMutable();
        point_.add(index, value);
        
        return this;
      }
      public Builder addPoint(
          de.ostfalia.robocup.message.MsgPoint.Point.Builder builderForValue) {
        ensurePointIsMutable();
        point_.add(builderForValue.build());
        
        return this;
      }
      public Builder addPoint(
          int index, de.ostfalia.robocup.message.MsgPoint.Point.Builder builderForValue) {
        ensurePointIsMutable();
        point_.add(index, builderForValue.build());
        
        return this;
      }
      public Builder addAllPoint(
          java.lang.Iterable<? extends de.ostfalia.robocup.message.MsgPoint.Point> values) {
        ensurePointIsMutable();
        super.addAll(values, point_);
        
        return this;
      }
      public Builder clearPoint() {
        point_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        
        return this;
      }
      public Builder removePoint(int index) {
        ensurePointIsMutable();
        point_.remove(index);
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:protobuf.PointCloud)
    }
    
    static {
      defaultInstance = new PointCloud(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protobuf.PointCloud)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
