/*
 * motionassigns.h
 *
 *  Created on: 23.03.2010
 *      Author: Stefan
 */

#ifndef MOTIONASSIGNS_H_
#define MOTIONASSIGNS_H_

#define flash	// Define "flash" as empty to remove from generated header file
#include "movements/HunoBasic.h"

struct MotionData {
	unsigned char *PT;//*TT;
	unsigned char *DT;//*ET;
	unsigned char *IT;//*PT;
	unsigned int *NumOfFrames;//*DT;
	unsigned int *RunTime;//*IT;
	unsigned char (*PoT)[18];//*FT;
	unsigned char (*TT)[18];//*RT;
	unsigned char (*ET)[18];//*PoT;
	int NumberOfScenes;
	int NumberOfwCK;
};

struct MotionData scenes_motionList[] = {

	// 0. GETUPBACK
		{
		 HUNOBASIC_GETUPBACK_WM_RuntimePGain,
		 HUNOBASIC_GETUPBACK_WM_RuntimeDGain,
		 HUNOBASIC_GETUPBACK_WM_RuntimeIGain,
		 HUNOBASIC_GETUPBACK_WM_Frames,
		 HUNOBASIC_GETUPBACK_WM_TrTime,
		 HUNOBASIC_GETUPBACK_WM_Position,
		 HUNOBASIC_GETUPBACK_WM_Torque,
		 HUNOBASIC_GETUPBACK_WM_Port,
		 HUNOBASIC_GETUPBACK_WM_NUM_OF_SCENES,
		 HUNOBASIC_GETUPBACK_WM_NUM_OF_WCKS
	},{
			//1
			GETUP_FRONT_RuntimePGain,
			GETUP_FRONT_RuntimeDGain,
			GETUP_FRONT_RuntimeIGain,
			GETUP_FRONT_Frames,
			GETUP_FRONT_TrTime,
			GETUP_FRONT_Position,
			GETUP_FRONT_Torque,
			GETUP_FRONT_Port,
			GETUP_FRONT_NUM_OF_SCENES,
			GETUP_FRONT_NUM_OF_WCKS
			},{
	//2
		KICK_COPPER_RIGHT_RuntimePGain,
		KICK_COPPER_RIGHT_RuntimeDGain,
		KICK_COPPER_RIGHT_RuntimeIGain,
		KICK_COPPER_RIGHT_Frames,
		KICK_COPPER_RIGHT_TrTime,
		KICK_COPPER_RIGHT_Position,
		KICK_COPPER_RIGHT_Torque,
		KICK_COPPER_RIGHT_Port,
		KICK_COPPER_RIGHT_NUM_OF_SCENES,
		KICK_COPPER_RIGHT_NUM_OF_WCKS
	},{//3
			KICK_LEFT_COPPER_RuntimePGain,
			KICK_LEFT_COPPER_RuntimeDGain,
			KICK_LEFT_COPPER_RuntimeIGain,
			KICK_LEFT_COPPER_Frames,
			KICK_LEFT_COPPER_TrTime,
			KICK_LEFT_COPPER_Position,
			KICK_LEFT_COPPER_Torque,
			KICK_LEFT_COPPER_Port,
			KICK_LEFT_COPPER_NUM_OF_SCENES,
			KICK_LEFT_COPPER_NUM_OF_WCKS
			},{
	//4
		HUNODEMO_HI_Stand_RuntimePGain,
		HUNODEMO_HI_Stand_RuntimeDGain,
		HUNODEMO_HI_Stand_RuntimeIGain,
		HUNODEMO_HI_Stand_Frames,
		HUNODEMO_HI_Stand_TrTime,
		HUNODEMO_HI_Stand_Position,
		HUNODEMO_HI_Stand_Torque,
		HUNODEMO_HI_Stand_Port,
		HUNODEMO_HI_Stand_NUM_OF_SCENES,
		HUNODEMO_HI_Stand_NUM_OF_WCKS
		},{//5
		KICK_LOCUTUS_LEFT_RuntimePGain,
		KICK_LOCUTUS_LEFT_RuntimeDGain,
		KICK_LOCUTUS_LEFT_RuntimeIGain,
		KICK_LOCUTUS_LEFT_Frames,
		KICK_LOCUTUS_LEFT_TrTime,
		KICK_LOCUTUS_LEFT_Position,
		KICK_LOCUTUS_LEFT_Torque,
		KICK_LOCUTUS_LEFT_Port,
		KICK_LOCUTUS_LEFT_NUM_OF_SCENES,
		KICK_LOCUTUS_LEFT_NUM_OF_WCKS
		},{//6
		KICK_LOCUTUS_RIGHT_RuntimePGain,
		KICK_LOCUTUS_RIGHT_RuntimeDGain,
		KICK_LOCUTUS_RIGHT_RuntimeIGain,
		KICK_LOCUTUS_RIGHT_Frames,
		KICK_LOCUTUS_RIGHT_TrTime,
		KICK_LOCUTUS_RIGHT_Position,
		KICK_LOCUTUS_RIGHT_Torque,
		KICK_LOCUTUS_RIGHT_Port,
		KICK_LOCUTUS_RIGHT_NUM_OF_SCENES,
		KICK_LOCUTUS_RIGHT_NUM_OF_WCKS
		},{//7
				TORJUMP_RuntimePGain,
				TORJUMP_RuntimeDGain,
				TORJUMP_RuntimeIGain,
				TORJUMP_Frames,
				TORJUMP_TrTime,
				TORJUMP_Position,
				TORJUMP_Torque,
				TORJUMP_Port,
				TORJUMP_NUM_OF_SCENES,
				TORJUMP_NUM_OF_WCKS
				}
		,{//8
				KICK_JONNY_LEFT_RuntimePGain,
				KICK_JONNY_LEFT_RuntimeDGain,
				KICK_JONNY_LEFT_RuntimeIGain,
				KICK_JONNY_LEFT_Frames,
				KICK_JONNY_LEFT_TrTime,
				KICK_JONNY_LEFT_Position,
				KICK_JONNY_LEFT_Torque,
				KICK_JONNY_LEFT_Port,
				KICK_JONNY_LEFT_NUM_OF_SCENES,
				KICK_JONNY_LEFT_NUM_OF_WCKS
				},{//9
						KICK_JONNY_RIGHT_RuntimePGain,
						KICK_JONNY_RIGHT_RuntimeDGain,
						KICK_JONNY_RIGHT_RuntimeIGain,
						KICK_JONNY_RIGHT_Frames,
						KICK_JONNY_RIGHT_TrTime,
						KICK_JONNY_RIGHT_Position,
						KICK_JONNY_RIGHT_Torque,
						KICK_JONNY_RIGHT_Port,
						KICK_JONNY_RIGHT_NUM_OF_SCENES,
						KICK_JONNY_RIGHT_NUM_OF_WCKS
						},{//10
								KICK_HUGH_RECHTS_RuntimePGain,
								KICK_HUGH_RECHTS_RuntimeDGain,
								KICK_HUGH_RECHTS_RuntimeIGain,
								KICK_HUGH_RECHTS_Frames,
								KICK_HUGH_RECHTS_TrTime,
								KICK_HUGH_RECHTS_Position,
								KICK_HUGH_RECHTS_Torque,
								KICK_HUGH_RECHTS_Port,
								KICK_HUGH_RECHTS_NUM_OF_SCENES,
								KICK_HUGH_RECHTS_NUM_OF_WCKS
												},
						{//11
								KICK_LEFT_HUGH_RuntimePGain,
								KICK_LEFT_HUGH_RuntimeDGain,
								KICK_LEFT_HUGH_RuntimeIGain,
								KICK_LEFT_HUGH_Frames,
								KICK_LEFT_HUGH_TrTime,
								KICK_LEFT_HUGH_Position,
								KICK_LEFT_HUGH_Torque,
								KICK_LEFT_HUGH_Port,
								KICK_LEFT_HUGH_NUM_OF_SCENES,
								KICK_LEFT_HUGH_NUM_OF_WCKS
					    },{
			//12
			GETUPFRONT_JONNY_RuntimePGain,
			GETUPFRONT_JONNY_RuntimeDGain,
			GETUPFRONT_JONNY_RuntimeIGain,
			GETUPFRONT_JONNY_Frames,
			GETUPFRONT_JONNY_TrTime,
			GETUPFRONT_JONNY_Position,
			GETUPFRONT_JONNY_Torque,
			GETUPFRONT_JONNY_Port,
			GETUPFRONT_JONNY_NUM_OF_SCENES,
			GETUPFRONT_JONNY_NUM_OF_WCKS
			},
			{//13
			GETUPFRONT_COPPER_RuntimePGain,
			GETUPFRONT_COPPER_RuntimeDGain,
			GETUPFRONT_COPPER_RuntimeIGain,
			GETUPFRONT_COPPER_Frames,
			GETUPFRONT_COPPER_TrTime,
			GETUPFRONT_COPPER_Position,
			GETUPFRONT_COPPER_Torque,
			GETUPFRONT_COPPER_Port,
			GETUPFRONT_COPPER_NUM_OF_SCENES,
			GETUPFRONT_COPPER_NUM_OF_WCKS
			},{//14
			AUFSTEHENHUGH_RuntimePGain,
			AUFSTEHENHUGH_RuntimeDGain,
			AUFSTEHENHUGH_RuntimeIGain,
			AUFSTEHENHUGH_Frames,
			AUFSTEHENHUGH_TrTime,
			AUFSTEHENHUGH_Position,
			AUFSTEHENHUGH_Torque,
			AUFSTEHENHUGH_Port,
			AUFSTEHENHUGH_NUM_OF_SCENES,
			AUFSTEHENHUGH_NUM_OF_WCKS
		},{//15
				KICK_LEFT_LOCUTUS_SUPER_RuntimePGain,
				KICK_LEFT_LOCUTUS_SUPER_RuntimeDGain,
				KICK_LEFT_LOCUTUS_SUPER_RuntimeIGain,
				KICK_LEFT_LOCUTUS_SUPER_Frames,
				KICK_LEFT_LOCUTUS_SUPER_TrTime,
				KICK_LEFT_LOCUTUS_SUPER_Position,
				KICK_LEFT_LOCUTUS_SUPER_Torque,
				KICK_LEFT_LOCUTUS_SUPER_Port,
				KICK_LEFT_LOCUTUS_SUPER_NUM_OF_SCENES,
				KICK_LEFT_LOCUTUS_SUPER_NUM_OF_WCKS
		},{//16
			 HUNOBASIC_GETUPBACK2_WM_RuntimePGain,
			 HUNOBASIC_GETUPBACK2_WM_RuntimeDGain,
			 HUNOBASIC_GETUPBACK2_WM_RuntimeIGain,
			 HUNOBASIC_GETUPBACK2_WM_Frames,
			 HUNOBASIC_GETUPBACK2_WM_TrTime,
			 HUNOBASIC_GETUPBACK2_WM_Position,
			 HUNOBASIC_GETUPBACK2_WM_Torque,
			 HUNOBASIC_GETUPBACK2_WM_Port,
			 HUNOBASIC_GETUPBACK2_WM_NUM_OF_SCENES,
			 HUNOBASIC_GETUPBACK2_WM_NUM_OF_WCKS
		},{//17
			KICK_LEFT_HUGH_SUPER_RuntimePGain,
			KICK_LEFT_HUGH_SUPER_RuntimeDGain,
			KICK_LEFT_HUGH_SUPER_RuntimeIGain,
			KICK_LEFT_HUGH_SUPER_Frames,
			KICK_LEFT_HUGH_SUPER_TrTime,
			KICK_LEFT_HUGH_SUPER_Position,
			KICK_LEFT_HUGH_SUPER_Torque,
			KICK_LEFT_HUGH_SUPER_Port,
			KICK_LEFT_HUGH_SUPER_NUM_OF_SCENES,
			KICK_LEFT_HUGH_SUPER_NUM_OF_WCKS
		},{//18
			GETUPBACKLOCUTUS_RuntimePGain,
			GETUPBACKLOCUTUS_RuntimeDGain,
			GETUPBACKLOCUTUS_RuntimeIGain,
			GETUPBACKLOCUTUS_Frames,
			GETUPBACKLOCUTUS_TrTime,
			GETUPBACKLOCUTUS_Position,
			GETUPBACKLOCUTUS_Torque,
			GETUPBACKLOCUTUS_Port,
			GETUPBACKLOCUTUS_NUM_OF_SCENES,
			GETUPBACKLOCUTUS_NUM_OF_WCKS
		},{//19
				KICK_RIGHT_HUGH_RICHTIG_RuntimePGain,
				KICK_RIGHT_HUGH_RICHTIG_RuntimeDGain,
				KICK_RIGHT_HUGH_RICHTIG_RuntimeIGain,
				KICK_RIGHT_HUGH_RICHTIG_Frames,
				KICK_RIGHT_HUGH_RICHTIG_TrTime,
				KICK_RIGHT_HUGH_RICHTIG_Position,
				KICK_RIGHT_HUGH_RICHTIG_Torque,
				KICK_RIGHT_HUGH_RICHTIG_Port,
				KICK_RIGHT_HUGH_RICHTIG_NUM_OF_SCENES,
				KICK_RIGHT_HUGH_RICHTIG_NUM_OF_WCKS
			},{//20
					TorwartJumpRight_RuntimePGain,
					TorwartJumpRight_RuntimeDGain,
					TorwartJumpRight_RuntimeIGain,
					TorwartJumpRight_Frames,
					TorwartJumpRight_TrTime,
					TorwartJumpRight_Position,
					TorwartJumpRight_Torque,
					TorwartJumpRight_Port,
					TorwartJumpRight_NUM_OF_SCENES,
					TorwartJumpRight_NUM_OF_WCKS
				},{//21
					TorwartJumpLeft_RuntimePGain,
					TorwartJumpLeft_RuntimeDGain,
					TorwartJumpLeft_RuntimeIGain,
					TorwartJumpLeft_Frames,
					TorwartJumpLeft_TrTime,
					TorwartJumpLeft_Position,
					TorwartJumpLeft_Torque,
					TorwartJumpLeft_Port,
					TorwartJumpLeft_NUM_OF_SCENES,
					TorwartJumpLeft_NUM_OF_WCKS
				},{//22
						ScussRechts1010_RuntimePGain,
						ScussRechts1010_RuntimeDGain,
						ScussRechts1010_RuntimeIGain,
						ScussRechts1010_Frames,
						ScussRechts1010_TrTime,
						ScussRechts1010_Position,
						ScussRechts1010_Torque,
						ScussRechts1010_Port,
						ScussRechts1010_NUM_OF_SCENES,
						ScussRechts1010_NUM_OF_WCKS
						}
			,{//23
			HUNOBASIC_GETUPBACK_HUGH_RuntimePGain,
			HUNOBASIC_GETUPBACK_HUGH_RuntimeDGain,
			HUNOBASIC_GETUPBACK_HUGH_RuntimeIGain,
			HUNOBASIC_GETUPBACK_HUGH_Frames,
			HUNOBASIC_GETUPBACK_HUGH_TrTime,
			HUNOBASIC_GETUPBACK_HUGH_Position,
			HUNOBASIC_GETUPBACK_HUGH_Torque,
			HUNOBASIC_GETUPBACK_HUGH_Port,
			HUNOBASIC_GETUPBACK_HUGH_NUM_OF_SCENES,
			HUNOBASIC_GETUPBACK_HUGH_NUM_OF_WCKS
		},{//24
				BettleMotion_RuntimePGain,
				BettleMotion_RuntimeDGain,
				BettleMotion_RuntimeIGain,
				BettleMotion_Frames,
				BettleMotion_TrTime,
				BettleMotion_Position,
				BettleMotion_Torque,
				BettleMotion_Port,
				BettleMotion_NUM_OF_SCENES,
				BettleMotion_NUM_OF_WCKS
			}};

#endif /* MOTIONASSIGNS_H_ */
