// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Blackboard.proto

package de.ostfalia.robocup.message;

public final class MsgBlackboard {
  private MsgBlackboard() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface BlackboardOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // repeated .protobuf.Blackboard.Representation representations = 1;
    java.util.List<de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation> 
        getRepresentationsList();
    de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation getRepresentations(int index);
    int getRepresentationsCount();
  }
  public static final class Blackboard extends
      com.google.protobuf.GeneratedMessageLite
      implements BlackboardOrBuilder {
    // Use Blackboard.newBuilder() to construct.
    private Blackboard(Builder builder) {
      super(builder);
    }
    private Blackboard(boolean noInit) {}
    
    private static final Blackboard defaultInstance;
    public static Blackboard getDefaultInstance() {
      return defaultInstance;
    }
    
    public Blackboard getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public interface RepresentationOrBuilder
        extends com.google.protobuf.MessageLiteOrBuilder {
      
      // required string name = 1;
      boolean hasName();
      String getName();
      
      // required string type = 2;
      boolean hasType();
      String getType();
      
      // optional bytes data = 3;
      boolean hasData();
      com.google.protobuf.ByteString getData();
    }
    public static final class Representation extends
        com.google.protobuf.GeneratedMessageLite
        implements RepresentationOrBuilder {
      // Use Representation.newBuilder() to construct.
      private Representation(Builder builder) {
        super(builder);
      }
      private Representation(boolean noInit) {}
      
      private static final Representation defaultInstance;
      public static Representation getDefaultInstance() {
        return defaultInstance;
      }
      
      public Representation getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      private int bitField0_;
      // required string name = 1;
      public static final int NAME_FIELD_NUMBER = 1;
      private java.lang.Object name_;
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            name_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // required string type = 2;
      public static final int TYPE_FIELD_NUMBER = 2;
      private java.lang.Object type_;
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getType() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            type_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // optional bytes data = 3;
      public static final int DATA_FIELD_NUMBER = 3;
      private com.google.protobuf.ByteString data_;
      public boolean hasData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      
      private void initFields() {
        name_ = "";
        type_ = "";
        data_ = com.google.protobuf.ByteString.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getTypeBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, data_);
        }
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getTypeBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, data_);
        }
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation, Builder>
          implements de.ostfalia.robocup.message.MsgBlackboard.Blackboard.RepresentationOrBuilder {
        // Construct using de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private void maybeForceBuilderInitialization() {
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          data_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation getDefaultInstanceForType() {
          return de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation.getDefaultInstance();
        }
        
        public de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation build() {
          de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation buildPartial() {
          de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation result = new de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.type_ = type_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.data_ = data_;
          result.bitField0_ = to_bitField0_;
          return result;
        }
        
        public Builder mergeFrom(de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation other) {
          if (other == de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation.getDefaultInstance()) return this;
          if (other.hasName()) {
            setName(other.getName());
          }
          if (other.hasType()) {
            setType(other.getType());
          }
          if (other.hasData()) {
            setData(other.getData());
          }
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasName()) {
            
            return false;
          }
          if (!hasType()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                
                return this;
              default: {
                if (!parseUnknownField(input, extensionRegistry, tag)) {
                  
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                name_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                type_ = input.readBytes();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                data_ = input.readBytes();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required string name = 1;
        private java.lang.Object name_ = "";
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setName(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          
          return this;
        }
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          
          return this;
        }
        void setName(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          name_ = value;
          
        }
        
        // required string type = 2;
        private java.lang.Object type_ = "";
        public boolean hasType() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public String getType() {
          java.lang.Object ref = type_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            type_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setType(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          type_ = value;
          
          return this;
        }
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000002);
          type_ = getDefaultInstance().getType();
          
          return this;
        }
        void setType(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000002;
          type_ = value;
          
        }
        
        // optional bytes data = 3;
        private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
        public boolean hasData() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public com.google.protobuf.ByteString getData() {
          return data_;
        }
        public Builder setData(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          data_ = value;
          
          return this;
        }
        public Builder clearData() {
          bitField0_ = (bitField0_ & ~0x00000004);
          data_ = getDefaultInstance().getData();
          
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:protobuf.Blackboard.Representation)
      }
      
      static {
        defaultInstance = new Representation(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:protobuf.Blackboard.Representation)
    }
    
    // repeated .protobuf.Blackboard.Representation representations = 1;
    public static final int REPRESENTATIONS_FIELD_NUMBER = 1;
    private java.util.List<de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation> representations_;
    public java.util.List<de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation> getRepresentationsList() {
      return representations_;
    }
    public java.util.List<? extends de.ostfalia.robocup.message.MsgBlackboard.Blackboard.RepresentationOrBuilder> 
        getRepresentationsOrBuilderList() {
      return representations_;
    }
    public int getRepresentationsCount() {
      return representations_.size();
    }
    public de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation getRepresentations(int index) {
      return representations_.get(index);
    }
    public de.ostfalia.robocup.message.MsgBlackboard.Blackboard.RepresentationOrBuilder getRepresentationsOrBuilder(
        int index) {
      return representations_.get(index);
    }
    
    private void initFields() {
      representations_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getRepresentationsCount(); i++) {
        if (!getRepresentations(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < representations_.size(); i++) {
        output.writeMessage(1, representations_.get(i));
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < representations_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, representations_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static de.ostfalia.robocup.message.MsgBlackboard.Blackboard parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.ostfalia.robocup.message.MsgBlackboard.Blackboard parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.ostfalia.robocup.message.MsgBlackboard.Blackboard parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.ostfalia.robocup.message.MsgBlackboard.Blackboard parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.ostfalia.robocup.message.MsgBlackboard.Blackboard parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.ostfalia.robocup.message.MsgBlackboard.Blackboard parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.ostfalia.robocup.message.MsgBlackboard.Blackboard parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.ostfalia.robocup.message.MsgBlackboard.Blackboard parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.ostfalia.robocup.message.MsgBlackboard.Blackboard parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.ostfalia.robocup.message.MsgBlackboard.Blackboard parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.ostfalia.robocup.message.MsgBlackboard.Blackboard prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          de.ostfalia.robocup.message.MsgBlackboard.Blackboard, Builder>
        implements de.ostfalia.robocup.message.MsgBlackboard.BlackboardOrBuilder {
      // Construct using de.ostfalia.robocup.message.MsgBlackboard.Blackboard.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        representations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public de.ostfalia.robocup.message.MsgBlackboard.Blackboard getDefaultInstanceForType() {
        return de.ostfalia.robocup.message.MsgBlackboard.Blackboard.getDefaultInstance();
      }
      
      public de.ostfalia.robocup.message.MsgBlackboard.Blackboard build() {
        de.ostfalia.robocup.message.MsgBlackboard.Blackboard result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private de.ostfalia.robocup.message.MsgBlackboard.Blackboard buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        de.ostfalia.robocup.message.MsgBlackboard.Blackboard result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public de.ostfalia.robocup.message.MsgBlackboard.Blackboard buildPartial() {
        de.ostfalia.robocup.message.MsgBlackboard.Blackboard result = new de.ostfalia.robocup.message.MsgBlackboard.Blackboard(this);
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          representations_ = java.util.Collections.unmodifiableList(representations_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.representations_ = representations_;
        return result;
      }
      
      public Builder mergeFrom(de.ostfalia.robocup.message.MsgBlackboard.Blackboard other) {
        if (other == de.ostfalia.robocup.message.MsgBlackboard.Blackboard.getDefaultInstance()) return this;
        if (!other.representations_.isEmpty()) {
          if (representations_.isEmpty()) {
            representations_ = other.representations_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureRepresentationsIsMutable();
            representations_.addAll(other.representations_);
          }
          
        }
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getRepresentationsCount(); i++) {
          if (!getRepresentations(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation.Builder subBuilder = de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addRepresentations(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .protobuf.Blackboard.Representation representations = 1;
      private java.util.List<de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation> representations_ =
        java.util.Collections.emptyList();
      private void ensureRepresentationsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          representations_ = new java.util.ArrayList<de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation>(representations_);
          bitField0_ |= 0x00000001;
         }
      }
      
      public java.util.List<de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation> getRepresentationsList() {
        return java.util.Collections.unmodifiableList(representations_);
      }
      public int getRepresentationsCount() {
        return representations_.size();
      }
      public de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation getRepresentations(int index) {
        return representations_.get(index);
      }
      public Builder setRepresentations(
          int index, de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRepresentationsIsMutable();
        representations_.set(index, value);
        
        return this;
      }
      public Builder setRepresentations(
          int index, de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation.Builder builderForValue) {
        ensureRepresentationsIsMutable();
        representations_.set(index, builderForValue.build());
        
        return this;
      }
      public Builder addRepresentations(de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRepresentationsIsMutable();
        representations_.add(value);
        
        return this;
      }
      public Builder addRepresentations(
          int index, de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureRepresentationsIsMutable();
        representations_.add(index, value);
        
        return this;
      }
      public Builder addRepresentations(
          de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation.Builder builderForValue) {
        ensureRepresentationsIsMutable();
        representations_.add(builderForValue.build());
        
        return this;
      }
      public Builder addRepresentations(
          int index, de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation.Builder builderForValue) {
        ensureRepresentationsIsMutable();
        representations_.add(index, builderForValue.build());
        
        return this;
      }
      public Builder addAllRepresentations(
          java.lang.Iterable<? extends de.ostfalia.robocup.message.MsgBlackboard.Blackboard.Representation> values) {
        ensureRepresentationsIsMutable();
        super.addAll(values, representations_);
        
        return this;
      }
      public Builder clearRepresentations() {
        representations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        
        return this;
      }
      public Builder removeRepresentations(int index) {
        ensureRepresentationsIsMutable();
        representations_.remove(index);
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:protobuf.Blackboard)
    }
    
    static {
      defaultInstance = new Blackboard(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protobuf.Blackboard)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
