// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "FieldLines.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
// @@protoc_insertion_point(includes)

namespace protobuf {

void protobuf_ShutdownFile_FieldLines_2eproto() {
  delete FieldLines::default_instance_;
}

void protobuf_AddDesc_FieldLines_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf::protobuf_AddDesc_Line_2eproto();
  FieldLines::default_instance_ = new FieldLines();
  FieldLines::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_FieldLines_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_FieldLines_2eproto {
  StaticDescriptorInitializer_FieldLines_2eproto() {
    protobuf_AddDesc_FieldLines_2eproto();
  }
} static_descriptor_initializer_FieldLines_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int FieldLines::kLineFieldNumber;
#endif  // !_MSC_VER

FieldLines::FieldLines()
  : ::google::protobuf::MessageLite() {
  SharedCtor();
}

void FieldLines::InitAsDefaultInstance() {
}

FieldLines::FieldLines(const FieldLines& from)
  : ::google::protobuf::MessageLite() {
  SharedCtor();
  MergeFrom(from);
}

void FieldLines::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

FieldLines::~FieldLines() {
  SharedDtor();
}

void FieldLines::SharedDtor() {
  if (this != default_instance_) {
  }
}

void FieldLines::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const FieldLines& FieldLines::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_FieldLines_2eproto();  return *default_instance_;
}

FieldLines* FieldLines::default_instance_ = NULL;

FieldLines* FieldLines::New() const {
  return new FieldLines;
}

void FieldLines::Clear() {
  line_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

bool FieldLines::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .protobuf.Line line = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_line:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_line()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(10)) goto parse_line;
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void FieldLines::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // repeated .protobuf.Line line = 1;
  for (int i = 0; i < this->line_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      1, this->line(i), output);
  }
  
}

int FieldLines::ByteSize() const {
  int total_size = 0;
  
  // repeated .protobuf.Line line = 1;
  total_size += 1 * this->line_size();
  for (int i = 0; i < this->line_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->line(i));
  }
  
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FieldLines::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const FieldLines*>(&from));
}

void FieldLines::MergeFrom(const FieldLines& from) {
  GOOGLE_CHECK_NE(&from, this);
  line_.MergeFrom(from.line_);
}

void FieldLines::CopyFrom(const FieldLines& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FieldLines::IsInitialized() const {
  
  for (int i = 0; i < line_size(); i++) {
    if (!this->line(i).IsInitialized()) return false;
  }
  return true;
}

void FieldLines::Swap(FieldLines* other) {
  if (other != this) {
    line_.Swap(&other->line_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::std::string FieldLines::GetTypeName() const {
  return "protobuf.FieldLines";
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf

// @@protoc_insertion_point(global_scope)
