// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BodyStatus.proto

#ifndef PROTOBUF_BodyStatus_2eproto__INCLUDED
#define PROTOBUF_BodyStatus_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include "ServoStatus.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_BodyStatus_2eproto();
void protobuf_AssignDesc_BodyStatus_2eproto();
void protobuf_ShutdownFile_BodyStatus_2eproto();

class BodyStatus;

// ===================================================================

class BodyStatus : public ::google::protobuf::MessageLite {
 public:
  BodyStatus();
  virtual ~BodyStatus();
  
  BodyStatus(const BodyStatus& from);
  
  inline BodyStatus& operator=(const BodyStatus& from) {
    CopyFrom(from);
    return *this;
  }
  
  static const BodyStatus& default_instance();
  
  void Swap(BodyStatus* other);
  
  // implements Message ----------------------------------------------
  
  BodyStatus* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const BodyStatus& from);
  void MergeFrom(const BodyStatus& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::std::string GetTypeName() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional double pan = 1;
  inline bool has_pan() const;
  inline void clear_pan();
  static const int kPanFieldNumber = 1;
  inline double pan() const;
  inline void set_pan(double value);
  
  // optional double tilt = 2;
  inline bool has_tilt() const;
  inline void clear_tilt();
  static const int kTiltFieldNumber = 2;
  inline double tilt() const;
  inline void set_tilt(double value);
  
  // required double voltage = 3;
  inline bool has_voltage() const;
  inline void clear_voltage();
  static const int kVoltageFieldNumber = 3;
  inline double voltage() const;
  inline void set_voltage(double value);
  
  // repeated .protobuf.ServoStatus servos = 4;
  inline int servos_size() const;
  inline void clear_servos();
  static const int kServosFieldNumber = 4;
  inline const ::protobuf::ServoStatus& servos(int index) const;
  inline ::protobuf::ServoStatus* mutable_servos(int index);
  inline ::protobuf::ServoStatus* add_servos();
  inline const ::google::protobuf::RepeatedPtrField< ::protobuf::ServoStatus >&
      servos() const;
  inline ::google::protobuf::RepeatedPtrField< ::protobuf::ServoStatus >*
      mutable_servos();
  
  // @@protoc_insertion_point(class_scope:protobuf.BodyStatus)
 private:
  inline void set_has_pan();
  inline void clear_has_pan();
  inline void set_has_tilt();
  inline void clear_has_tilt();
  inline void set_has_voltage();
  inline void clear_has_voltage();
  
  double pan_;
  double tilt_;
  double voltage_;
  ::google::protobuf::RepeatedPtrField< ::protobuf::ServoStatus > servos_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_BodyStatus_2eproto();
  friend void protobuf_AssignDesc_BodyStatus_2eproto();
  friend void protobuf_ShutdownFile_BodyStatus_2eproto();
  
  void InitAsDefaultInstance();
  static BodyStatus* default_instance_;
};
// ===================================================================


// ===================================================================

// BodyStatus

// optional double pan = 1;
inline bool BodyStatus::has_pan() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BodyStatus::set_has_pan() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BodyStatus::clear_has_pan() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BodyStatus::clear_pan() {
  pan_ = 0;
  clear_has_pan();
}
inline double BodyStatus::pan() const {
  return pan_;
}
inline void BodyStatus::set_pan(double value) {
  set_has_pan();
  pan_ = value;
}

// optional double tilt = 2;
inline bool BodyStatus::has_tilt() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BodyStatus::set_has_tilt() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BodyStatus::clear_has_tilt() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BodyStatus::clear_tilt() {
  tilt_ = 0;
  clear_has_tilt();
}
inline double BodyStatus::tilt() const {
  return tilt_;
}
inline void BodyStatus::set_tilt(double value) {
  set_has_tilt();
  tilt_ = value;
}

// required double voltage = 3;
inline bool BodyStatus::has_voltage() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void BodyStatus::set_has_voltage() {
  _has_bits_[0] |= 0x00000004u;
}
inline void BodyStatus::clear_has_voltage() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void BodyStatus::clear_voltage() {
  voltage_ = 0;
  clear_has_voltage();
}
inline double BodyStatus::voltage() const {
  return voltage_;
}
inline void BodyStatus::set_voltage(double value) {
  set_has_voltage();
  voltage_ = value;
}

// repeated .protobuf.ServoStatus servos = 4;
inline int BodyStatus::servos_size() const {
  return servos_.size();
}
inline void BodyStatus::clear_servos() {
  servos_.Clear();
}
inline const ::protobuf::ServoStatus& BodyStatus::servos(int index) const {
  return servos_.Get(index);
}
inline ::protobuf::ServoStatus* BodyStatus::mutable_servos(int index) {
  return servos_.Mutable(index);
}
inline ::protobuf::ServoStatus* BodyStatus::add_servos() {
  return servos_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::protobuf::ServoStatus >&
BodyStatus::servos() const {
  return servos_;
}
inline ::google::protobuf::RepeatedPtrField< ::protobuf::ServoStatus >*
BodyStatus::mutable_servos() {
  return &servos_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_BodyStatus_2eproto__INCLUDED
