// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Vector2D.proto

#ifndef PROTOBUF_Vector2D_2eproto__INCLUDED
#define PROTOBUF_Vector2D_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_Vector2D_2eproto();
void protobuf_AssignDesc_Vector2D_2eproto();
void protobuf_ShutdownFile_Vector2D_2eproto();

class Vector2D;

// ===================================================================

class Vector2D : public ::google::protobuf::MessageLite {
 public:
  Vector2D();
  virtual ~Vector2D();
  
  Vector2D(const Vector2D& from);
  
  inline Vector2D& operator=(const Vector2D& from) {
    CopyFrom(from);
    return *this;
  }
  
  static const Vector2D& default_instance();
  
  void Swap(Vector2D* other);
  
  // implements Message ----------------------------------------------
  
  Vector2D* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const Vector2D& from);
  void MergeFrom(const Vector2D& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::std::string GetTypeName() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required double angle = 1;
  inline bool has_angle() const;
  inline void clear_angle();
  static const int kAngleFieldNumber = 1;
  inline double angle() const;
  inline void set_angle(double value);
  
  // required double length = 2;
  inline bool has_length() const;
  inline void clear_length();
  static const int kLengthFieldNumber = 2;
  inline double length() const;
  inline void set_length(double value);
  
  // @@protoc_insertion_point(class_scope:protobuf.Vector2D)
 private:
  inline void set_has_angle();
  inline void clear_has_angle();
  inline void set_has_length();
  inline void clear_has_length();
  
  double angle_;
  double length_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_Vector2D_2eproto();
  friend void protobuf_AssignDesc_Vector2D_2eproto();
  friend void protobuf_ShutdownFile_Vector2D_2eproto();
  
  void InitAsDefaultInstance();
  static Vector2D* default_instance_;
};
// ===================================================================


// ===================================================================

// Vector2D

// required double angle = 1;
inline bool Vector2D::has_angle() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Vector2D::set_has_angle() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Vector2D::clear_has_angle() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Vector2D::clear_angle() {
  angle_ = 0;
  clear_has_angle();
}
inline double Vector2D::angle() const {
  return angle_;
}
inline void Vector2D::set_angle(double value) {
  set_has_angle();
  angle_ = value;
}

// required double length = 2;
inline bool Vector2D::has_length() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Vector2D::set_has_length() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Vector2D::clear_has_length() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Vector2D::clear_length() {
  length_ = 0;
  clear_has_length();
}
inline double Vector2D::length() const {
  return length_;
}
inline void Vector2D::set_length(double value) {
  set_has_length();
  length_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace protobuf

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Vector2D_2eproto__INCLUDED
