// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_image.proto

package de.ostfalia.robocup.message;

public final class MsgImageData {
  private MsgImageData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public enum ImageFormat
      implements com.google.protobuf.Internal.EnumLite {
    YUV422_IMAGE(0, 1),
    BAYER_IMAGE(1, 2),
    RGB_IMAGE(2, 3),
    ;
    
    public static final int YUV422_IMAGE_VALUE = 1;
    public static final int BAYER_IMAGE_VALUE = 2;
    public static final int RGB_IMAGE_VALUE = 3;
    
    
    public final int getNumber() { return value; }
    
    public static ImageFormat valueOf(int value) {
      switch (value) {
        case 1: return YUV422_IMAGE;
        case 2: return BAYER_IMAGE;
        case 3: return RGB_IMAGE;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ImageFormat>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ImageFormat>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ImageFormat>() {
            public ImageFormat findValueByNumber(int number) {
              return ImageFormat.valueOf(number);
            }
          };
    
    private final int value;
    
    private ImageFormat(int index, int value) {
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:protobuf.ImageFormat)
  }
  
  public interface ImageDataOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // required .protobuf.ImageFormat format = 1;
    boolean hasFormat();
    de.ostfalia.robocup.message.MsgImageData.ImageFormat getFormat();
    
    // required bytes data = 2;
    boolean hasData();
    com.google.protobuf.ByteString getData();
    
    // required bool compressed = 3 [default = false];
    boolean hasCompressed();
    boolean getCompressed();
    
    // required int32 width = 4;
    boolean hasWidth();
    int getWidth();
    
    // required int32 height = 5;
    boolean hasHeight();
    int getHeight();
  }
  public static final class ImageData extends
      com.google.protobuf.GeneratedMessageLite
      implements ImageDataOrBuilder {
    // Use ImageData.newBuilder() to construct.
    private ImageData(Builder builder) {
      super(builder);
    }
    private ImageData(boolean noInit) {}
    
    private static final ImageData defaultInstance;
    public static ImageData getDefaultInstance() {
      return defaultInstance;
    }
    
    public ImageData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // required .protobuf.ImageFormat format = 1;
    public static final int FORMAT_FIELD_NUMBER = 1;
    private de.ostfalia.robocup.message.MsgImageData.ImageFormat format_;
    public boolean hasFormat() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public de.ostfalia.robocup.message.MsgImageData.ImageFormat getFormat() {
      return format_;
    }
    
    // required bytes data = 2;
    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    
    // required bool compressed = 3 [default = false];
    public static final int COMPRESSED_FIELD_NUMBER = 3;
    private boolean compressed_;
    public boolean hasCompressed() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public boolean getCompressed() {
      return compressed_;
    }
    
    // required int32 width = 4;
    public static final int WIDTH_FIELD_NUMBER = 4;
    private int width_;
    public boolean hasWidth() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getWidth() {
      return width_;
    }
    
    // required int32 height = 5;
    public static final int HEIGHT_FIELD_NUMBER = 5;
    private int height_;
    public boolean hasHeight() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getHeight() {
      return height_;
    }
    
    private void initFields() {
      format_ = de.ostfalia.robocup.message.MsgImageData.ImageFormat.YUV422_IMAGE;
      data_ = com.google.protobuf.ByteString.EMPTY;
      compressed_ = false;
      width_ = 0;
      height_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasFormat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCompressed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWidth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeight()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, format_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, data_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, compressed_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, width_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, height_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, format_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, compressed_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, width_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, height_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static de.ostfalia.robocup.message.MsgImageData.ImageData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.ostfalia.robocup.message.MsgImageData.ImageData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.ostfalia.robocup.message.MsgImageData.ImageData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static de.ostfalia.robocup.message.MsgImageData.ImageData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static de.ostfalia.robocup.message.MsgImageData.ImageData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.ostfalia.robocup.message.MsgImageData.ImageData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static de.ostfalia.robocup.message.MsgImageData.ImageData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.ostfalia.robocup.message.MsgImageData.ImageData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static de.ostfalia.robocup.message.MsgImageData.ImageData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static de.ostfalia.robocup.message.MsgImageData.ImageData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.ostfalia.robocup.message.MsgImageData.ImageData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          de.ostfalia.robocup.message.MsgImageData.ImageData, Builder>
        implements de.ostfalia.robocup.message.MsgImageData.ImageDataOrBuilder {
      // Construct using de.ostfalia.robocup.message.MsgImageData.ImageData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        format_ = de.ostfalia.robocup.message.MsgImageData.ImageFormat.YUV422_IMAGE;
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        compressed_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        width_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        height_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public de.ostfalia.robocup.message.MsgImageData.ImageData getDefaultInstanceForType() {
        return de.ostfalia.robocup.message.MsgImageData.ImageData.getDefaultInstance();
      }
      
      public de.ostfalia.robocup.message.MsgImageData.ImageData build() {
        de.ostfalia.robocup.message.MsgImageData.ImageData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private de.ostfalia.robocup.message.MsgImageData.ImageData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        de.ostfalia.robocup.message.MsgImageData.ImageData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public de.ostfalia.robocup.message.MsgImageData.ImageData buildPartial() {
        de.ostfalia.robocup.message.MsgImageData.ImageData result = new de.ostfalia.robocup.message.MsgImageData.ImageData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.format_ = format_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.compressed_ = compressed_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.width_ = width_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.height_ = height_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(de.ostfalia.robocup.message.MsgImageData.ImageData other) {
        if (other == de.ostfalia.robocup.message.MsgImageData.ImageData.getDefaultInstance()) return this;
        if (other.hasFormat()) {
          setFormat(other.getFormat());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasCompressed()) {
          setCompressed(other.getCompressed());
        }
        if (other.hasWidth()) {
          setWidth(other.getWidth());
        }
        if (other.hasHeight()) {
          setHeight(other.getHeight());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasFormat()) {
          
          return false;
        }
        if (!hasData()) {
          
          return false;
        }
        if (!hasCompressed()) {
          
          return false;
        }
        if (!hasWidth()) {
          
          return false;
        }
        if (!hasHeight()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              de.ostfalia.robocup.message.MsgImageData.ImageFormat value = de.ostfalia.robocup.message.MsgImageData.ImageFormat.valueOf(rawValue);
              if (value != null) {
                bitField0_ |= 0x00000001;
                format_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              data_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              compressed_ = input.readBool();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              width_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              height_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .protobuf.ImageFormat format = 1;
      private de.ostfalia.robocup.message.MsgImageData.ImageFormat format_ = de.ostfalia.robocup.message.MsgImageData.ImageFormat.YUV422_IMAGE;
      public boolean hasFormat() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public de.ostfalia.robocup.message.MsgImageData.ImageFormat getFormat() {
        return format_;
      }
      public Builder setFormat(de.ostfalia.robocup.message.MsgImageData.ImageFormat value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        format_ = value;
        
        return this;
      }
      public Builder clearFormat() {
        bitField0_ = (bitField0_ & ~0x00000001);
        format_ = de.ostfalia.robocup.message.MsgImageData.ImageFormat.YUV422_IMAGE;
        
        return this;
      }
      
      // required bytes data = 2;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        
        return this;
      }
      
      // required bool compressed = 3 [default = false];
      private boolean compressed_ ;
      public boolean hasCompressed() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public boolean getCompressed() {
        return compressed_;
      }
      public Builder setCompressed(boolean value) {
        bitField0_ |= 0x00000004;
        compressed_ = value;
        
        return this;
      }
      public Builder clearCompressed() {
        bitField0_ = (bitField0_ & ~0x00000004);
        compressed_ = false;
        
        return this;
      }
      
      // required int32 width = 4;
      private int width_ ;
      public boolean hasWidth() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getWidth() {
        return width_;
      }
      public Builder setWidth(int value) {
        bitField0_ |= 0x00000008;
        width_ = value;
        
        return this;
      }
      public Builder clearWidth() {
        bitField0_ = (bitField0_ & ~0x00000008);
        width_ = 0;
        
        return this;
      }
      
      // required int32 height = 5;
      private int height_ ;
      public boolean hasHeight() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getHeight() {
        return height_;
      }
      public Builder setHeight(int value) {
        bitField0_ |= 0x00000010;
        height_ = value;
        
        return this;
      }
      public Builder clearHeight() {
        bitField0_ = (bitField0_ & ~0x00000010);
        height_ = 0;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:protobuf.ImageData)
    }
    
    static {
      defaultInstance = new ImageData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:protobuf.ImageData)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
